name = "qic890"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Qic890"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

# [[require]]
# name = "mathlib"
# scope = "leanprover-community"
# rev = "v4.28.0"

[[require]]
name = "quantumInfo"
git = "https://github.com/Timeroot/Lean-QuantumInfo"
rev = "main"

[[lean_lib]]
name = "Qic890"
